# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 499)
        self.line = QtWidgets.QFrame(MainWindow)
        self.line.setGeometry(QtCore.QRect(20, 410, 441, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(MainWindow)
        self.line_2.setGeometry(QtCore.QRect(230, 10, 20, 391))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtWidgets.QWidget(MainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 201, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonAX = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonAX.setObjectName("pushButtonAX")
        self.gridLayout.addWidget(self.pushButtonAX, 0, 0, 1, 1)
        self.pushButtonCJ = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonCJ.setObjectName("pushButtonCJ")
        self.gridLayout.addWidget(self.pushButtonCJ, 1, 0, 1, 1)
        self.pushButtonLX = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonLX.setObjectName("pushButtonLX")
        self.gridLayout.addWidget(self.pushButtonLX, 1, 1, 1, 1)
        self.pushButtonJC = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonJC.setObjectName("pushButtonJC")
        self.gridLayout.addWidget(self.pushButtonJC, 2, 0, 1, 1)
        self.pushButtonGB = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonGB.setObjectName("pushButtonGB")
        self.gridLayout.addWidget(self.pushButtonGB, 2, 1, 1, 1)
        self.pushButtonBD = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonBD.setObjectName("pushButtonBD")
        self.gridLayout.addWidget(self.pushButtonBD, 3, 0, 1, 1)
        self.pushButtonFS = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonFS.setObjectName("pushButtonFS")
        self.gridLayout.addWidget(self.pushButtonFS, 4, 0, 1, 1)
        self.pushButtonJY = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonJY.setObjectName("pushButtonJY")
        self.gridLayout.addWidget(self.pushButtonJY, 5, 0, 1, 1)
        self.pushButtonPL = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonPL.setObjectName("pushButtonPL")
        self.gridLayout.addWidget(self.pushButtonPL, 3, 1, 1, 1)
        self.pushButtonTCT = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonTCT.setObjectName("pushButtonTCT")
        self.gridLayout.addWidget(self.pushButtonTCT, 0, 1, 1, 1)
        self.pushButtonCYT = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonCYT.setObjectName("pushButtonCYT")
        self.gridLayout.addWidget(self.pushButtonCYT, 4, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(MainWindow)
        self.layoutWidget1.setGeometry(QtCore.QRect(260, 20, 201, 381))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonBX = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonBX.setObjectName("pushButtonBX")
        self.gridLayout_2.addWidget(self.pushButtonBX, 1, 0, 1, 1)
        self.pushButtonHST = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonHST.setObjectName("pushButtonHST")
        self.gridLayout_2.addWidget(self.pushButtonHST, 0, 1, 1, 1)
        self.pushButtonMJT = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonMJT.setObjectName("pushButtonMJT")
        self.gridLayout_2.addWidget(self.pushButtonMJT, 3, 1, 1, 1)
        self.pushButtonHJ = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonHJ.setObjectName("pushButtonHJ")
        self.gridLayout_2.addWidget(self.pushButtonHJ, 5, 0, 1, 1)
        self.pushButtonTL = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonTL.setObjectName("pushButtonTL")
        self.gridLayout_2.addWidget(self.pushButtonTL, 1, 1, 1, 1)
        self.pushButtonFY = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonFY.setObjectName("pushButtonFY")
        self.gridLayout_2.addWidget(self.pushButtonFY, 3, 0, 1, 1)
        self.pushButtonDJ = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonDJ.setObjectName("pushButtonDJ")
        self.gridLayout_2.addWidget(self.pushButtonDJ, 4, 0, 1, 1)
        self.pushButtonMW = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonMW.setObjectName("pushButtonMW")
        self.gridLayout_2.addWidget(self.pushButtonMW, 2, 1, 1, 1)
        self.pushButtonYJ = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonYJ.setObjectName("pushButtonYJ")
        self.gridLayout_2.addWidget(self.pushButtonYJ, 0, 0, 1, 1)
        self.pushButtonQC = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonQC.setObjectName("pushButtonQC")
        self.gridLayout_2.addWidget(self.pushButtonQC, 2, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(MainWindow)
        self.textBrowser.setGeometry(QtCore.QRect(20, 430, 441, 51))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "便携式宏库V1.12 by 幻夜白狼"))
        self.pushButtonAX.setText(_translate("MainWindow", "傲血宏"))
        self.pushButtonCJ.setText(_translate("MainWindow", "藏剑宏"))
        self.pushButtonLX.setText(_translate("MainWindow", "凌雪宏"))
        self.pushButtonJC.setText(_translate("MainWindow", "剑纯宏"))
        self.pushButtonGB.setText(_translate("MainWindow", "丐帮宏"))
        self.pushButtonBD.setText(_translate("MainWindow", "霸刀宏"))
        self.pushButtonFS.setText(_translate("MainWindow", "分山宏"))
        self.pushButtonJY.setText(_translate("MainWindow", "惊羽宏"))
        self.pushButtonPL.setText(_translate("MainWindow", "蓬莱宏"))
        self.pushButtonTCT.setText(_translate("MainWindow", "铁牢宏"))
        self.pushButtonCYT.setText(_translate("MainWindow", "铁骨宏"))
        self.pushButtonBX.setText(_translate("MainWindow", "冰心宏"))
        self.pushButtonHST.setText(_translate("MainWindow", "洗髓宏"))
        self.pushButtonMJT.setText(_translate("MainWindow", "明尊宏"))
        self.pushButtonHJ.setText(_translate("MainWindow", "花间宏"))
        self.pushButtonTL.setText(_translate("MainWindow", "田螺宏"))
        self.pushButtonFY.setText(_translate("MainWindow", "焚影宏"))
        self.pushButtonDJ.setText(_translate("MainWindow", "毒经宏"))
        self.pushButtonMW.setText(_translate("MainWindow", "莫问宏"))
        self.pushButtonYJ.setText(_translate("MainWindow", "易筋宏"))
        self.pushButtonQC.setText(_translate("MainWindow", "气纯宏"))
