# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def slot(self):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1089, 506)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(40, 400, 1041, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(310, 10, 20, 391))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 261, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonAX = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonAX.setObjectName("pushButtonAX")
        self.gridLayout.addWidget(self.pushButtonAX, 0, 0, 1, 1)
        self.pushButtonCJ = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonCJ.setObjectName("pushButtonCJ")
        self.gridLayout.addWidget(self.pushButtonCJ, 1, 0, 1, 1)
        self.pushButtonLX = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonLX.setObjectName("pushButtonLX")
        self.gridLayout.addWidget(self.pushButtonLX, 1, 1, 1, 1)
        self.pushButtonJC = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonJC.setObjectName("pushButtonJC")
        self.gridLayout.addWidget(self.pushButtonJC, 2, 0, 1, 1)
        self.pushButtonGB = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonGB.setObjectName("pushButtonGB")
        self.gridLayout.addWidget(self.pushButtonGB, 2, 1, 1, 1)
        self.pushButtonBD = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonBD.setObjectName("pushButtonBD")
        self.gridLayout.addWidget(self.pushButtonBD, 3, 0, 1, 1)
        self.pushButtonFS = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonFS.setObjectName("pushButtonFS")
        self.gridLayout.addWidget(self.pushButtonFS, 4, 0, 1, 1)
        self.pushButtonJY = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonJY.setObjectName("pushButtonJY")
        self.gridLayout.addWidget(self.pushButtonJY, 5, 0, 1, 1)
        self.pushButtonPL = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonPL.setObjectName("pushButtonPL")
        self.gridLayout.addWidget(self.pushButtonPL, 3, 1, 1, 1)
        self.pushButtonTCT = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonTCT.setObjectName("pushButtonTCT")
        self.gridLayout.addWidget(self.pushButtonTCT, 0, 1, 1, 1)
        self.pushButtonCYT = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonCYT.setObjectName("pushButtonCYT")
        self.gridLayout.addWidget(self.pushButtonCYT, 4, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(340, 20, 271, 381))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonYJ = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonYJ.setObjectName("pushButtonYJ")
        self.gridLayout_2.addWidget(self.pushButtonYJ, 0, 0, 1, 1)
        self.pushButtonMJT = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonMJT.setObjectName("pushButtonMJT")
        self.gridLayout_2.addWidget(self.pushButtonMJT, 3, 1, 1, 1)
        self.pushButtonTL = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonTL.setObjectName("pushButtonTL")
        self.gridLayout_2.addWidget(self.pushButtonTL, 1, 1, 1, 1)
        self.pushButtonFY = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonFY.setObjectName("pushButtonFY")
        self.gridLayout_2.addWidget(self.pushButtonFY, 3, 0, 1, 1)
        self.pushButtonDJ = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonDJ.setObjectName("pushButtonDJ")
        self.gridLayout_2.addWidget(self.pushButtonDJ, 4, 0, 1, 1)
        self.pushButtonQC = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonQC.setObjectName("pushButtonQC")
        self.gridLayout_2.addWidget(self.pushButtonQC, 2, 0, 1, 1)
        self.pushButtonBX = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonBX.setObjectName("pushButtonBX")
        self.gridLayout_2.addWidget(self.pushButtonBX, 1, 0, 1, 1)
        self.pushButtonHST = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonHST.setObjectName("pushButtonHST")
        self.gridLayout_2.addWidget(self.pushButtonHST, 0, 1, 1, 1)
        self.pushButtonMW = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonMW.setObjectName("pushButtonMW")
        self.gridLayout_2.addWidget(self.pushButtonMW, 2, 1, 1, 1)
        self.pushButtonHJ = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonHJ.setObjectName("pushButtonHJ")
        self.gridLayout_2.addWidget(self.pushButtonHJ, 5, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(620, 20, 20, 381))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(640, 20, 431, 384))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.textScript = QtWidgets.QTextEdit(self.splitter)
        self.textScript.setObjectName("textScript")
        self.textDescription = QtWidgets.QTextEdit(self.splitter)
        self.textDescription.setObjectName("textDescription")

        self.retranslateUi(Dialog)
        self.pushButtonAX.clicked.connect(self.slot)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonAX.setText(_translate("Dialog", "傲血宏"))
        self.pushButtonCJ.setText(_translate("Dialog", "藏剑宏"))
        self.pushButtonLX.setText(_translate("Dialog", "凌雪宏"))
        self.pushButtonJC.setText(_translate("Dialog", "剑纯宏"))
        self.pushButtonGB.setText(_translate("Dialog", "丐帮宏"))
        self.pushButtonBD.setText(_translate("Dialog", "霸刀宏"))
        self.pushButtonFS.setText(_translate("Dialog", "分山宏"))
        self.pushButtonJY.setText(_translate("Dialog", "惊羽宏"))
        self.pushButtonPL.setText(_translate("Dialog", "蓬莱宏"))
        self.pushButtonTCT.setText(_translate("Dialog", "铁牢宏"))
        self.pushButtonCYT.setText(_translate("Dialog", "铁骨宏"))
        self.pushButtonYJ.setText(_translate("Dialog", "易筋宏"))
        self.pushButtonMJT.setText(_translate("Dialog", "明尊宏"))
        self.pushButtonTL.setText(_translate("Dialog", "田螺宏"))
        self.pushButtonFY.setText(_translate("Dialog", "焚影宏"))
        self.pushButtonDJ.setText(_translate("Dialog", "毒经宏"))
        self.pushButtonQC.setText(_translate("Dialog", "气纯宏"))
        self.pushButtonBX.setText(_translate("Dialog", "冰心宏"))
        self.pushButtonHST.setText(_translate("Dialog", "洗髓宏"))
        self.pushButtonMW.setText(_translate("Dialog", "莫问宏"))
        self.pushButtonHJ.setText(_translate("Dialog", "花间宏"))
